#Cluster
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kai-kafka-cluster
  namespace: kafka
  annotations:
    strimzi.io/kraft: enabled
spec:
  kafka:
    version: 3.9.0 # Specify desired Kafka version (ensure Strimzi 0.45 supports this)
    listeners:
      # Internal TLS listener on 9093 with SCRAM-SHA-512 authentication
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      # These internal topic settings must match the total number of 'broker' role replicas (which is 1 here)
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1 # Default for auto-created topics
      min.insync.replicas: 1      # Minimum ISR MUST be <= broker replica count
      # KRaft relies on metadata versioning - Strimzi manages this based on Kafka version
  # NO zookeeper section when KRaft is enabled
  entityOperator:
    topicOperator: {} # Enable Topic Operator
    userOperator: {}  # Enable User Operator
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: controller-broker # Name for this node pool
  namespace: kafka         # Same namespace as Kafka resource
  labels:
    strimzi.io/cluster: kai-kafka-cluster
spec:
  replicas: 1 # Single node in this pool. INCREASE TO 3+ FOR PRODUCTION/HA!
  roles:
    - controller # This node acts as a controller
    - broker     # This node also acts as a broker
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: 100Gi
        deleteClaim: false
        kraftMetadata: shared
  # Add resources, jvmOptions etc. here if needed for this pool
  # resources:
  #   requests:
  #     memory: 4Gi
  #     cpu: "1"
  #   limits:
  #     memory: 4Gi
  #     cpu: "2"
  # jvmOptions:
  #   "-Xms": "2g"
  #   "-Xmx": "2g"