#Cluster
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kai-kafka-cluster
  namespace: kafka
  annotations:
    strimzi.io/kraft: enabled
spec:
  kafka:
    version: 3.9.0
    replicas: 1
    listeners:
      # Internal TLS listener on 9093 with SCRAM-SHA-512 authentication
      - name: tls
        port: 9093
        type: internal
        tls: true
        authentication:
          type: scram-sha-512
      # Example internal plain listener (optional)
      # - name: plain
      #   port: 9092
      #   type: internal
      #   tls: false
    config:
      # Required KRaft configurations - Strimzi sets defaults based on replicas,
      # but explicitly setting these based on replica=1 is good practice.
      offsets.topic.replication.factor: 1       # Must be <= number of brokers
      transaction.state.log.replication.factor: 1 # Must be <= number of brokers
      transaction.state.log.min.isr: 1          # Must be <= number of brokers
      default.replication.factor: 1             # Default for auto-created topics
      min.insync.replicas: 1                    # Minimum ISR MUST be <= replica count
      # inter.broker.protocol.version: "3.9" # Strimzi usually sets this automatically based on spec.kafka.version
    storage:
      type: persistent-claim
      # Storage for combined controller/broker node
      size: 25Gi # Adjust storage size as needed (might need slightly more than ZK+Broker)
      deleteClaim: false # Keeps PVC if cluster is deleted
  # NO zookeeper section when KRaft is enabled
  entityOperator:
    topicOperator: {} # Enable Topic Operator
    userOperator: {}  # Enable User Operator
