# ArgoCD application configuration
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fs-ai-gul
  namespace: argocd

spec:
  project: default
  # Git repo source to link argocd to
  source:
    repoURL: https://github.com/irori-ab/fs-ai-ops-gul-kai.git
    targetRevision: HEAD
    path: manifests/fs-ai-gul
  # K8s cluster to make changes to
  destination:
    # endpoint for k8s api server/target k8s cluster. If namespace doesn't exist, argocd creates it.
    server: https://kubernetes.default.svc
    namespace: default  

    # Enable automatic sync - prevent direct changes to the cluster(selfHeal) and delete files in repo when deleted in cluster(prune)
    automated:
      selfHeal: true

---

# Kafka cluster App
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-cluster
  namespace: kafka

spec:
  project: default
  source:
    repoURL: https://github.com/irori-ab/fs-ai-ops-gul-kai.git
    targetRevision: HEAD
    path: manifests/kafka-cluster
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka  
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
